import type { TerminalColors } from "../config";

export type Preset = "dark" | "light";

export interface ThemeDef {
  id: string;
  label: string;
  preset: Preset;
  terminal: TerminalColors;
}

export const THEMES: ThemeDef[] = [
  {
    id: "pure-black",
    label: "Negro puro",
    preset: "dark",
    terminal: {
      bg: "#000000",
      fg: "#ffffff",
      cursor: "#ffffff",
      black: "#15161a",
      red: "#ef4444",
      green: "#22c55e",
      yellow: "#eab308",
      blue: "#3b82f6",
      magenta: "#d946ef",
      cyan: "#06b6d4",
      white: "#d4d4d8",
      brightBlack: "#52525b",
      brightRed: "#f87171",
      brightGreen: "#4ade80",
      brightYellow: "#facc15",
      brightBlue: "#60a5fa",
      brightMagenta: "#e879f9",
      brightCyan: "#22d3ee",
      brightWhite: "#ffffff",
    },
  },
  {
    id: "tokyo-night",
    label: "Tokyo Night",
    preset: "dark",
    terminal: {
      bg: "#1a1b26",
      fg: "#c0caf5",
      cursor: "#c0caf5",
      black: "#15161e",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#a9b1d6",
      brightBlack: "#414868",
      brightRed: "#ff899d",
      brightGreen: "#9fe044",
      brightYellow: "#faba4a",
      brightBlue: "#8db0ff",
      brightMagenta: "#c7a9ff",
      brightCyan: "#a4daff",
      brightWhite: "#c0caf5",
    },
  },
  {
    id: "catppuccin-mocha",
    label: "Catppuccin Mocha",
    preset: "dark",
    terminal: {
      bg: "#1e1e2e",
      fg: "#cdd6f4",
      cursor: "#f5e0dc",
      black: "#45475a",
      red: "#f38ba8",
      green: "#a6e3a1",
      yellow: "#f9e2af",
      blue: "#89b4fa",
      magenta: "#f5c2e7",
      cyan: "#94e2d5",
      white: "#bac2de",
      brightBlack: "#585b70",
      brightRed: "#f38ba8",
      brightGreen: "#a6e3a1",
      brightYellow: "#f9e2af",
      brightBlue: "#89b4fa",
      brightMagenta: "#f5c2e7",
      brightCyan: "#94e2d5",
      brightWhite: "#a6adc8",
    },
  },
  {
    id: "catppuccin-latte",
    label: "Claro (Catppuccin Latte)",
    preset: "light",
    terminal: {
      bg: "#eff1f5",
      fg: "#4c4f69",
      cursor: "#dc8a78",
      black: "#5c5f77",
      red: "#d20f39",
      green: "#40a02b",
      yellow: "#df8e1d",
      blue: "#1e66f5",
      magenta: "#ea76cb",
      cyan: "#179299",
      white: "#acb0be",
      brightBlack: "#6c6f85",
      brightRed: "#d20f39",
      brightGreen: "#40a02b",
      brightYellow: "#df8e1d",
      brightBlue: "#1e66f5",
      brightMagenta: "#ea76cb",
      brightCyan: "#179299",
      brightWhite: "#bcc0cc",
    },
  },
  {
    id: "dracula",
    label: "Dracula",
    preset: "dark",
    terminal: {
      bg: "#282a36",
      fg: "#f8f8f2",
      cursor: "#f8f8f2",
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
      brightBlack: "#6272a4",
      brightRed: "#ff6e6e",
      brightGreen: "#69ff94",
      brightYellow: "#ffffa5",
      brightBlue: "#d6acff",
      brightMagenta: "#ff92df",
      brightCyan: "#a4ffff",
      brightWhite: "#ffffff",
    },
  },
  {
    id: "nord",
    label: "Nord",
    preset: "dark",
    terminal: {
      bg: "#2e3440",
      fg: "#d8dee9",
      cursor: "#d8dee9",
      black: "#3b4252",
      red: "#bf616a",
      green: "#a3be8c",
      yellow: "#ebcb8b",
      blue: "#81a1c1",
      magenta: "#b48ead",
      cyan: "#88c0d0",
      white: "#e5e9f0",
      brightBlack: "#4c566a",
      brightRed: "#bf616a",
      brightGreen: "#a3be8c",
      brightYellow: "#ebcb8b",
      brightBlue: "#81a1c1",
      brightMagenta: "#b48ead",
      brightCyan: "#8fbcbb",
      brightWhite: "#eceff4",
    },
  },
  {
    id: "gruvbox",
    label: "Gruvbox",
    preset: "dark",
    terminal: {
      bg: "#282828",
      fg: "#ebdbb2",
      cursor: "#ebdbb2",
      black: "#282828",
      red: "#cc241d",
      green: "#98971a",
      yellow: "#d79921",
      blue: "#458588",
      magenta: "#b16286",
      cyan: "#689d6a",
      white: "#a89984",
      brightBlack: "#928374",
      brightRed: "#fb4934",
      brightGreen: "#b8bb26",
      brightYellow: "#fabd2f",
      brightBlue: "#83a598",
      brightMagenta: "#d3869b",
      brightCyan: "#8ec07c",
      brightWhite: "#ebdbb2",
    },
  },
  {
    id: "one-dark",
    label: "One Dark",
    preset: "dark",
    terminal: {
      bg: "#282c34",
      fg: "#abb2bf",
      cursor: "#5c6370",
      black: "#2c323c",
      red: "#e06c75",
      green: "#98c379",
      yellow: "#e5c07b",
      blue: "#61afef",
      magenta: "#c678dd",
      cyan: "#56b6c2",
      white: "#5c6370",
      brightBlack: "#3e4452",
      brightRed: "#e06c75",
      brightGreen: "#98c379",
      brightYellow: "#e5c07b",
      brightBlue: "#61afef",
      brightMagenta: "#c678dd",
      brightCyan: "#56b6c2",
      brightWhite: "#abb2bf",
    },
  },
  {
    id: "rose-pine",
    label: "Rosé Pine",
    preset: "dark",
    terminal: {
      bg: "#191724",
      fg: "#e0def4",
      cursor: "#524f67",
      black: "#26233a",
      red: "#eb6f92",
      green: "#31748f",
      yellow: "#f6c177",
      blue: "#9ccfd8",
      magenta: "#c4a7e7",
      cyan: "#ebbcba",
      white: "#e0def4",
      brightBlack: "#6e6a86",
      brightRed: "#eb6f92",
      brightGreen: "#31748f",
      brightYellow: "#f6c177",
      brightBlue: "#9ccfd8",
      brightMagenta: "#c4a7e7",
      brightCyan: "#ebbcba",
      brightWhite: "#e0def4",
    },
  },
  {
    id: "kanagawa",
    label: "Kanagawa",
    preset: "dark",
    terminal: {
      bg: "#1f1f28",
      fg: "#dcd7ba",
      cursor: "#c8c093",
      black: "#16161d",
      red: "#c34043",
      green: "#76946a",
      yellow: "#c0a36e",
      blue: "#7e9cd8",
      magenta: "#957fb8",
      cyan: "#6a9589",
      white: "#c8c093",
      brightBlack: "#727169",
      brightRed: "#e82424",
      brightGreen: "#98bb6c",
      brightYellow: "#e6c384",
      brightBlue: "#7fb4ca",
      brightMagenta: "#938aa9",
      brightCyan: "#7aa89f",
      brightWhite: "#dcd7ba",
    },
  },
  {
    id: "japan-night",
    label: "Japan Night",
    preset: "dark",
    terminal: {
      bg: "#0d0e1a",
      fg: "#e2e4f0",
      cursor: "#ff2d78",
      black: "#1a1b2e",
      red: "#ff4466",
      green: "#39d98a",
      yellow: "#ffd166",
      blue: "#4d9de0",
      magenta: "#e040fb",
      cyan: "#00e5ff",
      white: "#a9afc9",
      brightBlack: "#3d4166",
      brightRed: "#ff6b8a",
      brightGreen: "#57f5a8",
      brightYellow: "#ffe599",
      brightBlue: "#74b9ff",
      brightMagenta: "#ff2d78",
      brightCyan: "#18ffff",
      brightWhite: "#f0f2ff",
    },
  },
];

export function themeMatches(t: ThemeDef, c: TerminalColors): boolean {
  return (
    t.terminal.bg === c.bg &&
    t.terminal.fg === c.fg &&
    t.terminal.blue === c.blue &&
    t.terminal.green === c.green &&
    t.terminal.magenta === c.magenta
  );
}
